// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe6Np8_Da1QX63OaLswPadYHKTOorMoM8',
    appId: '1:297987988416:web:e9040cff52a7a71ea1c625',
    messagingSenderId: '297987988416',
    projectId: 'task-manager-99a0d',
    authDomain: 'task-manager-99a0d.firebaseapp.com',
    storageBucket: 'task-manager-99a0d.firebasestorage.app',
    measurementId: 'G-C6TY623DG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoUio5hwR2BMPJ3algFIbbrR8CZtPpsco',
    appId: '1:297987988416:android:e9193ea3faa72fbea1c625',
    messagingSenderId: '297987988416',
    projectId: 'task-manager-99a0d',
    storageBucket: 'task-manager-99a0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAciKMPSsQNmaE-T5XhI3vmbWkOKxdGRbo',
    appId: '1:297987988416:ios:75fc1e6614d13fbaa1c625',
    messagingSenderId: '297987988416',
    projectId: 'task-manager-99a0d',
    storageBucket: 'task-manager-99a0d.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAciKMPSsQNmaE-T5XhI3vmbWkOKxdGRbo',
    appId: '1:297987988416:ios:75fc1e6614d13fbaa1c625',
    messagingSenderId: '297987988416',
    projectId: 'task-manager-99a0d',
    storageBucket: 'task-manager-99a0d.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe6Np8_Da1QX63OaLswPadYHKTOorMoM8',
    appId: '1:297987988416:web:52fc88e56c74570fa1c625',
    messagingSenderId: '297987988416',
    projectId: 'task-manager-99a0d',
    authDomain: 'task-manager-99a0d.firebaseapp.com',
    storageBucket: 'task-manager-99a0d.firebasestorage.app',
    measurementId: 'G-S7JDZN0CTS',
  );
}
